### ISSUE TITLE
[bug]A error at ruby.py

### ISSUE THREAD

**Issue by cyw3** [terryyin/lizard#210]
python lizard.py path/to/project --CCN 10 --csv --working_threads 3 --sort cyclomatic_complexity -l javascript -l python -l objectivec -l ttcn -l php -l scala -l ruby -l swift

![image](https://user-images.githubusercontent.com/11549103/34096492-75a5cbfe-e410-11e7-9072-111bc9640ce9.png)

and I can not end the thread of working process.
![image](https://user-images.githubusercontent.com/11549103/34096793-a37f3c12-e411-11e7-8d52-ed9c34b98c20.png)

**Comment by cyw3** [comment]
And I use the command with "--working_threads" below:
python lizard.py path/to/project --CCN 10 --csv --sort cyclomatic_complexity -l javascript -l python -l objectivec -l ttcn -l php -l scala -l ruby -l swift

everything it is OK.

**Comment by baffles** [comment]
Is there a fix for this planned? Running on a single thread is a less than desireable workaround.

**Comment by terryyin** [comment]
Will look at this before the end of this week. During my 7 hours flight probably.

**Comment by cyw3** [comment]
It does not work with "--working_threads" in lizard 1.16.3
and crash:
`
$ python3 lizard.py -l ruby -t 3 /Users/xxx/Desktop/Test/ruby/rubyTest

================================================
  NLOC    CCN   token  PARAM  length  location
------------------------------------------------
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/xxx/.pyenv/versions/3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/xxx/.pyenv/versions/3.7.0/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/xxx/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/pool.py", line 470, in _handle_results
    task = get()
  File "/Users/xxx/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/Users/xxx/lizard-1.16.3/lizard_languages/ruby.py", line 12, in __new__
    return super(MyToken, cls).__new__(cls, value.group(0))
AttributeError: 'str' object has no attribute 'group'
`

**Comment by terryyin** [comment]
Let me see… Perhaps I can fix this without trying to be compatible with Python2.

Ruby syntax is hard for one time parsing to understand everything.
